//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Vegan { get; set; }
        public Nullable<bool> Vegetarian { get; set; }
        public Nullable<bool> GlutenFree { get; set; }
        public Nullable<bool> ChefRecommendation { get; set; }
        public decimal PriceSmall { get; set; }
        public Nullable<decimal> PriceBig { get; set; }
        public string Type { get; set; }
        public string Photo { get; set; }
        public int Sequence { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
