//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MenuCategoryId { get; set; }
        public System.Guid MenuSubCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Vegan { get; set; }
        public Nullable<bool> Vegetarian { get; set; }
        public Nullable<bool> GlutenFree { get; set; }
        public Nullable<bool> ChefRecommendation { get; set; }
        public decimal PriceSmall { get; set; }
        public Nullable<decimal> PriceBig { get; set; }
        public string Type { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Photo { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
        public virtual MenuSubCategory MenuSubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
