//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategory()
        {
            this.SubCategoryVsItems = new HashSet<SubCategoryVsItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Tittle { get; set; }
        public string Subtitle { get; set; }
        public string Footer { get; set; }
        public Nullable<int> Sequency { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategoryVsItem> SubCategoryVsItems { get; set; }
    }
}
