//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSubCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuSubCategory()
        {
            this.MenuItems = new HashSet<MenuItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid MenuCategoryId { get; set; }
        public string Tittle { get; set; }
        public string Subtitle { get; set; }
        public string Footer { get; set; }
        public Nullable<int> Sequency { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }
    }
}
