//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid MenuItemId { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
