//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public System.Guid Id { get; set; }
        public System.Guid RestaurantId { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
